version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: avito-postgres
    environment:
      POSTGRES_DB: avito
      POSTGRES_USER: avito
      POSTGRES_PASSWORD: avito
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - avito-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avito -d avito"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: avito-prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - avito-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: avito-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - avito-network
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: avito
      DB_PASSWORD: avito
      DB_NAME: avito
      DB_SSLMODE: disable
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - avito-network
    restart: unless-stopped

volumes:
  grafana_data:
  postgres_data:

networks:
  avito-network:
    driver: bridge